# Generated by Django 5.2.3 on 2025-07-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, help_text='Client name for this job task', max_length=200)),
                ('manufacture_stage', models.CharField(choices=[('cnc', 'CNC'), ('sanding', 'Sanding'), ('painting', 'Painting'), ('assembly', 'Assembly'), ('delivery', 'Delivery'), ('installation', 'Installation'), ('completed', 'Completed')], default='cnc', max_length=20)),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_started', help_text='Current progress of the job task', max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if the job task is completed')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
