# Generated by Django 5.2.3 on 2025-07-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client name for this project', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the project is completed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_started', help_text='Current progress of the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
