# Generated by Django 5.2.3 on 2025-07-07 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('client_name', models.CharField(blank=True, help_text='Client name for this job task', max_length=200)),
                ('stage', models.CharField(choices=[('cnc', 'CNC'), ('sanding', 'Sanding'), ('painting', 'Painting'), ('assembly', 'Assembly'), ('delivery', 'Delivery'), ('installation', 'Installation'), ('completed', 'Completed')], default='cnc', max_length=20)),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not_started', help_text='Current progress of the job task', max_length=20)),
                ('plans', models.FileField(blank=True, null=True, upload_to='job_tasks/plans/')),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.task',),
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('job', 'Job'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
